[package]
name = "barq"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.9.0"
ordered-float = "5.0.0"
thin-vec = "0.2.14"

[profile.release]
lto = true
panic = "abort"
strip = true
codegen-units = 1
