[package]
name = "barq"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.11.3", features = ["macros"] }
thin-vec = "0.2.14"

[profile.release]
lto = true
panic = "abort"
strip = true
codegen-units = 1
