const std = @import("std");

const Range = @import("Range.zig");

tag: Tag,
range: Range,

pub const Tag = enum(u8) {
    eof,
    invalid,
    identifier,
    special_identifier,
    string_literal,
    char_literal,
    int,
    float,
    open_paren,
    close_paren,
    open_brace,
    close_brace,
    open_bracket,
    close_bracket,
    comma,
    period,
    double_period,
    triple_period,
    colon,
    double_colon,
    semicolon,
    fat_arrow,
    plus,
    minus,
    star,
    divide,
    modulo,
    bool_not,
    bit_not,
    bit_and,
    bit_or,
    bit_xor,
    less_than,
    greater_than,
    less_or_eql,
    greater_or_eql,
    left_shift,
    right_shift,
    eql,
    not_eql,
    assign,
    colon_assign,
    plus_assign,
    minus_assign,
    star_assign,
    divide_assign,
    modulo_assign,
    bit_and_assign,
    bit_or_assign,
    bit_xor_assign,
    left_shift_assign,
    right_shift_assign,
    keyword_const,
    keyword_defer,
    keyword_struct,
    keyword_enum,
    keyword_fn,
    keyword_switch,
    keyword_if,
    keyword_else,
    keyword_while,
    keyword_break,
    keyword_continue,
    keyword_asm,
    keyword_as,
    keyword_return,
};

pub const keywords = std.StaticStringMap(Tag).initComptime(.{
    .{ "const", .keyword_const },
    .{ "defer", .keyword_defer },
    .{ "struct", .keyword_struct },
    .{ "enum", .keyword_enum },
    .{ "fn", .keyword_fn },
    .{ "switch", .keyword_switch },
    .{ "if", .keyword_if },
    .{ "else", .keyword_else },
    .{ "while", .keyword_while },
    .{ "break", .keyword_break },
    .{ "continue", .keyword_continue },
    .{ "asm", .keyword_asm },
    .{ "as", .keyword_as },
    .{ "return", .keyword_return },
});
