[package]
name = "cerium_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
cerium_ast = { path = "../ast" }
cerium_errors = { path = "../errors" }
cerium_lexer = { path = "../lexer" }
cerium_position = { path = "../position" }
cerium_ty = { path = "../ty" }
